apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: torq-operator

manifests:
  rawYaml:
    - k8s/*.yaml

build:
  local:
    concurrency: 1
    tryImportMissing: false
    useDockerCLI: false
    push: false # not push images to registry
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: fizanmuhammedfaisal/torq-operator
      context: .
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
          - dest: .
            src: "src/**/*.json"
          - dest: .
            src: "k8s/*.yaml"

deploy:
  kubectl: {}
