export const DOMAIN_ERROR_CODES = {
	ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
	NOT_FOUND: 'NOT_FOUND',
	CONFLICT: 'CONFLICT',
	INVALID_ARGUMENT: 'INVALID_ARGUMENT',
	INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
	DATABASE_ERROR: 'DATABASE_ERROR',
	INVALID_VERSION: 'INVALID_VERSION',
	INVALID_SPEC: 'INVALID_SPEC',
	SEMANTIC_VALIDATION_ERROR: 'SEMANTIC_VALIDATION_ERROR',
	UNAUTHENTICATED: 'UNAUTHENTICATED',
	FORBIDDEN: 'FORBIDDEN',
	RETRYABLE_TRIGGER_ERROR: 'RETRYABLE_TRIGGER_ERROR',
	BAD_REQUST: 'BAD_REQUST',
} as const;

export type DomainErrorCodes = (typeof DOMAIN_ERROR_CODES)[keyof typeof DOMAIN_ERROR_CODES];
