export const DOMAIN_ERROR_CODES = {
	ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
	NOT_FOUND: 'NOT_FOUND',
	INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
	DATABASE_ERROR: 'DATABASE_ERROR',
	INVALID_VERSION: 'INVALID_VERSION',
	INVALID_SPEC: 'INVALID_SPEC',
	SEMANTIC_VALIDATION_ERROR: 'SEMANTIC_VALIDATION_ERROR',
} as const;

export type DomainErrorCodes = (typeof DOMAIN_ERROR_CODES)[keyof typeof DOMAIN_ERROR_CODES];
