apiVersion: v1
kind: ConfigMap
metadata:
  name: operator-config
data:
  REDIS_URL: "redis://redis:6379"
  REDIS_HOST: "redis.torq.svc.cluster.local"
  REDIS_PORT: "6379"
  LOG_LEVEL: "debug"
  GRPC_HOST: "0.0.0.0"
  NODE_ENV: "development"
  API_SERVER_GRPC_BASE_URL: "http://torq-apiserver-grpc-service:50052"
  HOST: "0.0.0.0"
