apiVersion: v1
kind: ConfigMap
metadata:
  name: log-ingestor-config
  namespace: torq
data:
  REDIS_URL: "redis://redis:6379"
  REDIS_HOST: "redis.torq.svc.cluster.local"
  REDIS_PORT: "6379"
  LOG_LEVEL: "info"
  NODE_ENV: "development"

# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: log-ingestor-secret
#   namespace: torq
# type: Opaque
# data:
#   # values must be base64 encoded: echo -n "mypassword" | base64
#   SOME_API_KEY: "bXlwYXNzd29yZA=="
