apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-ingestor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-ingestor
  template:
    metadata:
      labels:
        app: log-ingestor
    spec:
      containers:
        - name: log-ingestor
          image: fizanmuhammedfaisal/torq-log-ingestor
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: log-ingestor-service
spec:
  selector:
    app: log-ingestor
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
