import type { Workflow } from '../types';

export const MOCK_WORKFLOWS: Workflow[] = [
	{
		id: 'wf-1',
		name: 'CI / Build & Test',
		description:
			'Install dependencies, lint, type-check, and run unit tests on every push',
		status: 'success',
		namespace: 'engineering-core',
		lastRun: '12m ago',
		duration: '2m 34s',
		steps: 5,
		successRate: [true, true, false, true, true, true, true, true, true, true],
	},
	{
		id: 'wf-2',
		name: 'Deploy to Staging',
		description:
			'Build Docker image, push to registry, deploy to staging cluster',
		status: 'running',
		namespace: 'platform-ops',
		lastRun: '1h ago',
		duration: '5m 12s',
		steps: 4,
		successRate: [true, true, true, true, true, true, false, true, true, true],
	},
	{
		id: 'wf-3',
		name: 'Database Migration',
		description:
			'Run pending migrations and seed test data for development environment',
		status: 'failed',
		namespace: 'engineering-core',
		lastRun: '3d ago',
		duration: '45s',
		steps: 3,
		successRate: [
			true,
			false,
			false,
			true,
			true,
			true,
			false,
			false,
			false,
			false,
		],
	},
	{
		id: 'wf-4',
		name: 'Nightly E2E Suite',
		description:
			'Full end-to-end tests against staging environment with browser automation',
		status: 'idle',
		namespace: 'qa-automation',
		lastRun: 'Yesterday',
		duration: '14m 08s',
		steps: 5,
		successRate: [true, true, true, true, true, true, true, true, true, true],
	},
	{
		id: 'wf-5',
		name: 'Daily Analytics Backup',
		description: 'Export telemetry data to cold storage on S3',
		status: 'success',
		namespace: 'data-team',
		lastRun: '14h ago',
		duration: '11m 42s',
		steps: 2,
		successRate: [true, true, false, true, true, true, true, true, true, true],
	},
	{
		id: 'wf-6',
		name: 'Cleanup Orphaned Resources',
		description:
			'Pruning dangling resources, old pods, and temporary AWS security groups',
		status: 'idle',
		namespace: 'platform-ops',
		lastRun: '2d ago',
		duration: '3m 15s',
		steps: 2,
		successRate: [true, true, true, true, true, true, true, true, true, true],
	},
];
