export const TOKENS = {
	WorkflowController: Symbol.for('WorkflowController'),
	WorkflowRouter: Symbol.for('WorkflowRouter'),
	HealthRouter: Symbol.for('HealthRouter'),
	AuthRouter: Symbol.for('AuthRouter'),
	AppRouter: Symbol.for('AppRouter'),
	EmailService: Symbol.for('EmailService'),
	SignInOTPStrategy: Symbol.for('SignInOTPStrategy'),
	EmailVerificationStrategy: Symbol.for('EmailVerificationStrategy'),
	ForgetPasswordStrategy: Symbol.for('ForgetPasswordStrategy'),
	SendOTPEmail: Symbol.for('SendOTPEmail'),
	SecretManagementService: Symbol.for('SecretManagementService'),
	WorkflowRepository: Symbol.for('WorkflowRepository'),
	SecretRepository: Symbol.for('SecretRepository'),
	WorkflowVersionRepository: Symbol.for('WorkflowVersionRepository'),
	WorkflowMapper: Symbol.for('WorkflowMapper'),
	SecretMapper: Symbol.for('SecretMapper'),
	WorkflowVersionMapper: Symbol.for('WorkflowVersionMapper'),
	SpecValidationService: Symbol.for('SpecValidationService'),
	UnitOfWork: Symbol.for('UnitOfWork'),
	AuthMacro: Symbol.for('AuthMacro'),
} as const;
