export const TOKENS = {
	HTTPServer: Symbol.for('HTTPServer'),
	GRPCServer: Symbol.for('GRPCServer'),
	WorkflowController: Symbol.for('WorkflowController'),
	WorkflowRouter: Symbol.for('WorkflowRouter'),
	HealthRouter: Symbol.for('HealthRouter'),
	AuthRouter: Symbol.for('AuthRouter'),
	AppRouter: Symbol.for('AppRouter'),
	EmailService: Symbol.for('EmailService'),
	SignInOTPStrategy: Symbol.for('SignInOTPStrategy'),
	EmailVerificationStrategy: Symbol.for('EmailVerificationStrategy'),
	ForgetPasswordStrategy: Symbol.for('ForgetPasswordStrategy'),
	SendOTPEmail: Symbol.for('SendOTPEmail'),
	SecretManagementService: Symbol.for('SecretManagementService'),
	WorkflowRepository: Symbol.for('WorkflowRepository'),
	SecretRepository: Symbol.for('SecretRepository'),
	WorkflowVersionRepository: Symbol.for('WorkflowVersionRepository'),
	WorkflowMapper: Symbol.for('WorkflowMapper'),
	SecretMapper: Symbol.for('SecretMapper'),
	WorkflowVersionMapper: Symbol.for('WorkflowVersionMapper'),
	SpecValidationService: Symbol.for('SpecValidationService'),

	UpsertSecretsUseCase: Symbol.for('UpsertSecretsUseCase'),
	GetSecretsUseCase: Symbol.for('GetSecretsUseCase'),
	GetWorkflowsUseCase: Symbol.for('GetWorkflowsUseCase'),
	RevealSecretUseCase: Symbol.for('RevealSecretUseCase'),
	TriggerWorkflowRunUseCase: Symbol.for('TriggerWorkflowRunUseCase'),
	CreateWorkflowUseCase: Symbol.for('CreateWorkflowUseCase'),
	GetWorkflowByIdUseCase: Symbol.for('GetWorkflowByIdUseCase'),
	WorkflowRunRepository: Symbol.for('WorkflowRunRepository'),
	OperatorService: Symbol.for('OperatorService'),
	UnitOfWork: Symbol.for('UnitOfWork'),
	AuthMacro: Symbol.for('AuthMacro'),
	ErrorMacro: Symbol.for('ErrorMacro'),
	RPCRouter: Symbol.for('RPCRouter'),
	GrpcClient: Symbol.for('GrpcClient'),
	WorkflowAggregateRepository: Symbol.for('WorkflowAggregateRepository'),
	WorkflowRunMapper: Symbol.for('WorkflowRunMapper'),
	RedisClient: Symbol.for('RedisClient'),

	// usecases
	GetWorkflowSpecUseCase: Symbol.for('GetWorkflowSpecUseCase'),
	UpdateWorkflowUseCase: Symbol.for('UpdateWorkflowUseCase'),

	//
	WorkflowRPCMapper: Symbol.for('WorkflowRPCMapper'),
	WorkflowRPCController: Symbol.for('WorkflowRPCController'),
	RunController: Symbol.for('RunController'),
	RunRouter: Symbol.for('RunRouter'),
	GetRunsUseCase: Symbol.for('GetRunsUseCase'),
} as const;
