export type RunPhase = 'PENDING' | 'RUNNING' | 'SUCCESS' | 'FAILED' | 'CANCELLED';
export type StepStatus = 'PENDING' | 'SCHEDULED' | 'RUNNING' | 'SUCCESS' | 'FAILED';

export interface StepSpec {
    name: string;
    needs: string[];
    runtime: { image: string };
    steps: { run: string }[];
    resources?: { cpu?: string; memory?: string };
    retry?: { attempts: number };
    timeout?: string;
}

export interface RunSpec {
    steps: StepSpec[];
    failFast: boolean;
    secrets: Secret[];
}

export interface Secret {
    name: string;
    envName: string;
    value: string;
}

export interface StepState {
    status: StepStatus;
    startedAt?: string;
    completedAt?: string;
    attempt: number;
}
/**
 * The Main Entity representint the state of a workflow run 
 * This is what the runner operates on and what the reconciler updates based on the state 
 */
export class WorkflowRunSnapshot {
    private constructor(
        public readonly metadata: {
            // name should be unique
            name: string;
            namespace: string;
            // generated by Runner
            uid: string;
            generation: number;
            resourceVersion: string;
            deletionTimestamp?: Date;
            finalizers?: string[];
        },
        //desired state
        public readonly spec: {
            workflowId: string;
            versionId: string;
            torqVersion: string;
            triggeredBy: string;
            createdAt?: string;
        },
        //actual state
        public readonly status?: {
            phase: RunPhase;
            startedAt?: string;
            completedAt?: string;
            reason?: string;
            observedGeneration?: number;
            steps: Record<string, StepState>;
        },
    ) { }
    public static create(props: {
        metadata: {
            name: string;
            namespace: string;
            uid: string;
            generation: number;
            resourceVersion: string;
            deletionTimestamp?: Date;
            finalizers?: string[];
        };
        spec: {
            workflowId: string;
            versionId: string;
            torqVersion: string;
            triggeredBy: string;
            createdAt?: string;
        };
        status?: {
            phase: RunPhase;
            startedAt?: string;
            completedAt?: string;
            reason?: string;
            observedGeneration?: number;
            steps: Record<string, StepState>;
        };
    }) {
        return new WorkflowRunSnapshot(props.metadata, props.spec, props.status);
    }
}
