apiVersion: v1
kind: ConfigMap
metadata:
  name: apiserver-config
data:
  REDIS_URL: "redis://redis:6379"
  REDIS_HOST: "redis.torq.svc.cluster.local"
  REDIS_PORT: "6379"
  BETTER_AUTH_URL: "http://localhost:31990"
  APP_EMAIL: "torq@torq.togatherapp.site"
  LOG_LEVEL: "debug"
  NODE_ENV: "development"
  MULTI_AUTH_ENABLED: "true"
  OPERATOR_GRPC_URL: "http://torq-operator-service:50051"
  GRPC_HOST: "0.0.0.0"

# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: log-ingestor-secret
#   namespace: torq
# type: Opaque
# data:
#   # values must be base64 encoded: echo -n "mypassword" | base64
#   SOME_API_KEY: "bXlwYXNzd29yZA=="
