apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: torq-apiserver 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: torq-apiserver 
  template:
    metadata:
      labels:
        app: torq-apiserver
    spec:
      containers:
        - name: torq-apiserver
          image: fizanmuhammedfaisal/torq-apiserver
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: apiserver-config
            - secretRef:
                name: apiserver-secret
--- 
apiVersion: v1 
kind: Service
metadata:
  name: torq-apiserver-service 
spec:
  selector:
    app: torq-apiserver
  ports:
    - name: http
      port: 4000 
      targetPort: 4000
    - name: grpc
      port: 50052
      targetPort: 50052
  type: NodePort